#+50% each new shop
shops: 
  shop28:
    COBBLESTONE;0: 1200
    STONE;0: 2400
    STAINED_CLAY;9: 3600
    STAINED_CLAY;0: 4800
    NETHERRACK;0: 6000
    STAINED_CLAY;5: 7200
    STAINED_CLAY;4: 8400
    ENDER_STONE;0: 9600
    STAINED_CLAY;2: 10800
    OBSIDIAN;0: 12000
    STAINED_CLAY;3: 13200
    STAINED_CLAY;14: 1440
    QUARTZ_BLOCK;0: 15600
    PRISMARINE;0: 16800
  shop27:
    COBBLESTONE;0: 1100
    STONE;0: 2200
    STAINED_CLAY;9: 3300
    STAINED_CLAY;0: 4400
    NETHERRACK;0: 5500
    STAINED_CLAY;5: 6600
    STAINED_CLAY;4: 7700
    ENDER_STONE;0: 8800
    STAINED_CLAY;2: 9900
    OBSIDIAN;0: 11000
    STAINED_CLAY;3: 12100
    STAINED_CLAY;14: 13200
    QUARTZ_BLOCK;0: 14300
    PRISMARINE;0: 15400
  shop26:
    COBBLESTONE;0: 1000
    STONE;0: 2000
    STAINED_CLAY;9: 3000
    STAINED_CLAY;0: 4000
    NETHERRACK;0: 5000
    STAINED_CLAY;5: 6000
    STAINED_CLAY;4: 7000
    ENDER_STONE;0: 8000
    STAINED_CLAY;2: 9000
    OBSIDIAN;0: 10000
    STAINED_CLAY;3: 11000
    STAINED_CLAY;14: 12000
    QUARTZ_BLOCK;0: 13000
    PRISMARINE;0: 14000
  shop25:
    COBBLESTONE;0: 900
    STONE;0: 1800
    STAINED_CLAY;9: 2700
    STAINED_CLAY;0: 3600
    NETHERRACK;0: 4500
    STAINED_CLAY;5: 5400
    STAINED_CLAY;4: 6300
    ENDER_STONE;0: 7200
    STAINED_CLAY;2: 8100
    OBSIDIAN;0: 9000
    STAINED_CLAY;3: 9900
    STAINED_CLAY;14: 10800
    QUARTZ_BLOCK;0: 11700
    PRISMARINE;0: 12600
  shop24:
    COBBLESTONE;0: 800
    STONE;0: 1600
    STAINED_CLAY;9: 2400
    STAINED_CLAY;0: 3200
    NETHERRACK;0: 4000
    STAINED_CLAY;5: 4800
    STAINED_CLAY;4: 5600
    ENDER_STONE;0: 6400
    STAINED_CLAY;2: 7200
    OBSIDIAN;0: 8000
    STAINED_CLAY;3: 8800
    STAINED_CLAY;14: 9600
    QUARTZ_BLOCK;0: 10400
    PRISMARINE;0: 11200
  shop23:
    COBBLESTONE;0: 700
    STONE;0: 1400
    STAINED_CLAY;9: 2100
    STAINED_CLAY;0: 2800
    NETHERRACK;0: 3500
    STAINED_CLAY;5: 4200
    STAINED_CLAY;4: 4900
    ENDER_STONE;0: 5600
    STAINED_CLAY;2: 6300
    OBSIDIAN;0: 7000
    STAINED_CLAY;3: 7700
    STAINED_CLAY;14: 8400
    QUARTZ_BLOCK;0: 9100
    PRISMARINE;0: 9800
  shop22:   
    COBBLESTONE;0: 600
    STONE;0: 900
    STAINED_CLAY;9: 1200
    STAINED_CLAY;0: 1800
    NETHERRACK;0: 2400
    STAINED_CLAY;5: 3000
    STAINED_CLAY;4: 3600
    ENDER_STONE;0: 4200
    STAINED_CLAY;2: 4800
    OBSIDIAN;0: 5400
    STAINED_CLAY;3: 6000
    STAINED_CLAY;14: 6600
    QUARTZ_BLOCK;0: 7200
    PRISMARINE;0: 7800
  shop21:
    COBBLESTONE;0: 500
    STONE;0: 750
    STAINED_CLAY;9: 1000
    STAINED_CLAY;0: 1500
    NETHERRACK;0: 2000
    STAINED_CLAY;5: 2500
    STAINED_CLAY;4: 3000
    ENDER_STONE;0: 3500
    STAINED_CLAY;2: 4000
    OBSIDIAN;0: 4500
    STAINED_CLAY;3: 5000
    STAINED_CLAY;14: 6500
    QUARTZ_BLOCK;0: 7000
    PRISMARINE;0: 7500
  shop20:
    COBBLESTONE;0: 400
    STONE;0: 600
    STAINED_CLAY;9: 800
    STAINED_CLAY;0: 1200
    NETHERRACK;0: 1600
    STAINED_CLAY;5: 2000
    STAINED_CLAY;4: 2400
    ENDER_STONE;0: 2800
    STAINED_CLAY;2: 3200
    OBSIDIAN;0: 3600
    STAINED_CLAY;3: 4000
    STAINED_CLAY;14: 4400
    QUARTZ_BLOCK;0: 4800
    PRISMARINE;0: 5200
  shop19:
    COBBLESTONE;0: 350
    STONE;0: 475
    STAINED_CLAY;9: 700
    STAINED_CLAY;0: 1050
    NETHERRACK;0: 1400
    STAINED_CLAY;5: 1750
    STAINED_CLAY;4: 2100
    ENDER_STONE;0: 2450
    STAINED_CLAY;2: 2800
    OBSIDIAN;0: 3150
    STAINED_CLAY;3: 3500
    STAINED_CLAY;14: 3850
    QUARTZ_BLOCK;0: 4200
    PRISMARINE;0: 4550
  shop18:
    COBBLESTONE;0: 300
    STONE;0: 450
    STAINED_CLAY;9: 600
    STAINED_CLAY;0: 900
    NETHERRACK;0: 1200
    STAINED_CLAY;5: 1500
    STAINED_CLAY;4: 1800
    ENDER_STONE;0: 2100
    STAINED_CLAY;2: 2400
    OBSIDIAN;0: 2700
    STAINED_CLAY;3: 3000
    STAINED_CLAY;14: 3300
    QUARTZ_BLOCK;0: 3600
    PRISMARINE;0: 3900
  shop17:
    COBBLESTONE;0: 250
    STONE;0: 325
    STAINED_CLAY;9: 500
    STAINED_CLAY;0: 750
    NETHERRACK;0: 1000
    STAINED_CLAY;5: 1250
    STAINED_CLAY;4: 1500
    ENDER_STONE;0: 1750
    STAINED_CLAY;2: 2000
    OBSIDIAN;0: 2250
    STAINED_CLAY;3: 2500
    STAINED_CLAY;14: 2750
    QUARTZ_BLOCK;0: 3000
    PRISMARINE;0: 3250
  shop16:
    COBBLESTONE;0: 200
    STONE;0: 300
    STAINED_CLAY;9: 400
    STAINED_CLAY;0: 600
    NETHERRACK;0: 800
    STAINED_CLAY;5: 1000
    STAINED_CLAY;4: 1200
    ENDER_STONE;0: 1400
    STAINED_CLAY;2: 1600
    OBSIDIAN;0: 1800
    STAINED_CLAY;3: 2000
    STAINED_CLAY;14: 2200
    QUARTZ_BLOCK;0: 2400
    PRISMARINE;0: 2600
  shop15:
    COBBLESTONE;0: 180
    STONE;0: 270
    STAINED_CLAY;9: 540
    STAINED_CLAY;0: 720
    NETHERRACK;0: 900
    STAINED_CLAY;5: 1080
    STAINED_CLAY;4: 1260
    ENDER_STONE;0: 1440
    STAINED_CLAY;2: 1620
    OBSIDIAN;0: 1800
    STAINED_CLAY;3: 1980
    STAINED_CLAY;14: 2160
    QUARTZ_BLOCK;0: 2340
    PRISMARINE;0: 2520
  shop14:
    COBBLESTONE;0: 160
    STONE;0: 220
    STAINED_CLAY;9: 320
    STAINED_CLAY;0: 480
    NETHERRACK;0: 640
    STAINED_CLAY;5: 800
    STAINED_CLAY;4: 960
    ENDER_STONE;0: 1120
    STAINED_CLAY;2: 1280
    OBSIDIAN;0: 1440
    STAINED_CLAY;3: 1600
    STAINED_CLAY;14: 1760
    QUARTZ_BLOCK;0: 1920
    PRISMARINE;0: 2080
  shop13:
    COBBLESTONE;0: 140
    STONE;0: 280
    STAINED_CLAY;9: 280
    STAINED_CLAY;0: 420
    NETHERRACK;0: 560
    STAINED_CLAY;5: 700
    STAINED_CLAY;4: 840
    ENDER_STONE;0: 960
    STAINED_CLAY;2: 1220
    OBSIDIAN;0: 1260
    STAINED_CLAY;3: 1400
    STAINED_CLAY;14: 1540
    QUARTZ_BLOCK;0: 1680
    PRISMARINE;0: 
  shop12:
    COBBLESTONE;0: 120
    STONE;0: 180
    STAINED_CLAY;9: 240
    STAINED_CLAY;0: 360
    NETHERRACK;0: 480
    STAINED_CLAY;5: 600
    STAINED_CLAY;4: 720
    ENDER_STONE;0: 840
    STAINED_CLAY;2: 960
    OBSIDIAN;0: 1080
    STAINED_CLAY;3: 1200
    STAINED_CLAY;14: 1320
    QUARTZ_BLOCK;0: 1440
    PRISMARINE;0: 1560
  shop11:
    COBBLESTONE;0: 100
    STONE;0: 150
    STAINED_CLAY;9: 200
    STAINED_CLAY;0: 300
    NETHERRACK;0: 400
    STAINED_CLAY;5: 500
    STAINED_CLAY;4: 600
    ENDER_STONE;0: 700
    STAINED_CLAY;2: 800
    OBSIDIAN;0: 900
    STAINED_CLAY;3: 1000
    STAINED_CLAY;14: 1100
    QUARTZ_BLOCK;0: 1200
    PRISMARINE;0: 1300
  shop10:
    COBBLESTONE;0: 90
    STONE;0: 135
    STAINED_CLAY;9: 180
    STAINED_CLAY;0: 270
    NETHERRACK;0: 360
    STAINED_CLAY;5: 450
    STAINED_CLAY;4: 540
    ENDER_STONE;0: 630
    STAINED_CLAY;2: 720
    OBSIDIAN;0: 810
    STAINED_CLAY;3: 900
    STAINED_CLAY;14: 990
    QUARTZ_BLOCK;0: 1110
    PRISMARINE;0: 1200
  shop9:
    COBBLESTONE;0: 80
    STONE;0: 120
    STAINED_CLAY;9: 160
    STAINED_CLAY;0: 240
    NETHERRACK;0: 320
    STAINED_CLAY;5: 400
    STAINED_CLAY;4: 480
    ENDER_STONE;0: 560
    STAINED_CLAY;2: 640
    OBSIDIAN;0: 720
    STAINED_CLAY;3: 800
    STAINED_CLAY;14: 880
    QUARTZ_BLOCK;0: 940
    PRISMARINE;0: 1020
  shop8:
    COBBLESTONE;0: 70
    STONE;0: 105
    STAINED_CLAY;9: 140
    STAINED_CLAY;0: 210
    NETHERRACK;0: 280
    STAINED_CLAY;5: 350
    STAINED_CLAY;4: 420
    ENDER_STONE;0: 490
    STAINED_CLAY;2: 560
    OBSIDIAN;0: 630
    STAINED_CLAY;3: 700
    STAINED_CLAY;14: 770
    QUARTZ_BLOCK;0: 840
    PRISMARINE;0: 910
  shop7:
    COBBLESTONE;0: 60
    STONE;0: 90
    STAINED_CLAY;9: 120
    STAINED_CLAY;0: 180
    NETHERRACK;0: 240
    STAINED_CLAY;5: 300
    STAINED_CLAY;4: 360
    ENDER_STONE;0: 420
    STAINED_CLAY;2: 480
    OBSIDIAN;0: 540
    STAINED_CLAY;3: 600
    STAINED_CLAY;14: 660
    QUARTZ_BLOCK;0: 720
    PRISMARINE;0: 680
  shop6:
    COBBLESTONE;0: 50
    STONE;0: 75
    STAINED_CLAY;9: 100
    STAINED_CLAY;0: 150
    NETHERRACK;0: 200
    STAINED_CLAY;5: 250
    STAINED_CLAY;4: 300
    ENDER_STONE;0: 350
    STAINED_CLAY;2: 400
    OBSIDIAN;0: 450
    STAINED_CLAY;3: 500
    STAINED_CLAY;14: 550
    QUARTZ_BLOCK;0: 600
    PRISMARINE;0: 650
  shop5:
    COBBLESTONE;0: 40
    STONE;0: 60
    STAINED_CLAY;9: 80
    STAINED_CLAY;0: 120
    NETHERRACK;0: 160
    STAINED_CLAY;5: 200
    STAINED_CLAY;4: 240
    ENDER_STONE;0: 280
    STAINED_CLAY;2: 320
    OBSIDIAN;0: 360
    STAINED_CLAY;3: 400
    STAINED_CLAY;14: 440
    QUARTZ_BLOCK;0: 480
    PRISMARINE;0: 520
  shop5:
    COBBLESTONE;0: 30
    STONE;0: 45
    STAINED_CLAY;9: 60
    STAINED_CLAY;0: 90
    NETHERRACK;0: 120
    STAINED_CLAY;5: 150
    STAINED_CLAY;4: 180
    ENDER_STONE;0: 210
    STAINED_CLAY;2: 240
    OBSIDIAN;0: 270
    STAINED_CLAY;3: 300
    STAINED_CLAY;14: 330
    QUARTZ_BLOCK;0: 360
    PRISMARINE;0: 390
  shop4:
    COBBLESTONE;0: 25
    STONE;0: 37.5
    STAINED_CLAY;9: 50
    STAINED_CLAY;0: 75
    NETHERRACK;0: 100
    STAINED_CLAY;5: 125
    STAINED_CLAY;4: 150
    ENDER_STONE;0: 175
    STAINED_CLAY;2: 200
    OBSIDIAN;0: 225
    STAINED_CLAY;3: 250
    STAINED_CLAY;14: 275
    QUARTZ_BLOCK;0: 300
    PRISMARINE;0: 325
  shop3:
    COBBLESTONE;0: 20
    STONE;0: 30
    STAINED_CLAY;9: 40
    STAINED_CLAY;0: 60
    NETHERRACK;0: 80
    STAINED_CLAY;5: 100
    STAINED_CLAY;4: 120
    ENDER_STONE;0: 140
    STAINED_CLAY;2: 160
    OBSIDIAN;0: 180
    STAINED_CLAY;3: 200
    STAINED_CLAY;14: 220
    QUARTZ_BLOCK;0: 240
    PRISMARINE;0: 260
  shop2:
    COBBLESTONE;0: 15
    STONE;0: 22.5
    STAINED_CLAY;9: 30
    STAINED_CLAY;0: 45
    NETHERRACK;0: 60
    STAINED_CLAY;5: 75
    STAINED_CLAY;4: 90
    ENDER_STONE;0: 105
    STAINED_CLAY;2: 120
    OBSIDIAN;0: 135
    STAINED_CLAY;3: 150
    STAINED_CLAY;14: 165
    QUARTZ_BLOCK;0: 170
    PRISMARINE;0: 195
  shop1:
    COBBLESTONE;0: 10
    STONE;0: 15
    STAINED_CLAY;9: 20
    STAINED_CLAY;0: 30
    NETHERRACK;0: 40
    STAINED_CLAY;5: 50
    STAINED_CLAY;4: 60
    ENDER_STONE;0: 70
    STAINED_CLAY;2: 80
    OBSIDIAN;0: 90
    STAINED_CLAY;3: 100
    STAINED_CLAY;14: 110
    QUARTZ_BLOCK;0: 130
    PRISMARINE;0: 140
multis:
  player:
    Synysterrr: 1.15
  permission:
    eternal: 1.0
    immortal: 0.75
    reaper: 0.5
    resurrected: 0.4
    sinner: 0.3
    decaying: 0.2
    dead: 0.1
    